inhibit_all_warnings!
pod 'RDVTabBarController'
pod 'HMSegmentedControl'
pod 'MJRefresh'
platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'JSONModel'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'DTCoreText', '~> 1.6.16'
pod 'FrameAccessor'


pod 'ShareSDK3'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'ShareSDK3/ShareSDKPlatforms/GooglePlus'